# Generated by Django 3.0.7 on 2020-11-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileHandle', '0002_auto_20201124_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicpaper',
            options={'managed': False},
        ),
    ]
