# Generated by Django 3.0.7 on 2020-11-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileHandle', '0003_auto_20201125_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicpaper',
            options={},
        ),
    ]
